=== robbiewu008/open-eBackup/src/ProtectManager/component/PM_System_Base_Common_Service/src/pm-plugins/pm-database-plugins/pm-sqlserver-protection-plugin/src/main/resources/jsonschema/SQLServer-clusterInstance_define.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "title",
  "properties": {
    "uuid": {
      "type": "string",
      "description": "集群实例uuid"
    },
    "name": {
      "type": "string",
      "description": "集群实例名称"
    },
    "type": {
      "type": "string",
      "description": "资源类型"
    },
    "subType": {
      "type": "string",
      "description": "资源子类型"
    },
    "parentUuid": {
      "type": "string",
      "description": "实例所在集群uuid"
    },
    "extendInfo": {
      "type": "object",
      "properties": {
        "networkName": {
          "type": "string"
        }
      }
    },
    "dependencies": {"$ref": "classpath:jsonschema/SQLServer-base.json#/agentDependencies"},
    "auth": {"$ref": "classpath:jsonschema/SQLServer-base.json#/auth"}
  },
  "required": [
    "subType",
    "type",
    "name",
    "parentUuid",
    "extendInfo",
    "dependencies",
    "auth"
  ]
}

=== robbiewu008/open-eBackup/src/ProtectManager/component/PM_System_Base_Common_Service/src/pm-common/src/test/resources/jsonschema/Mysql-register-test.json
{
  "name": "test",
  "type": "Database",
  "subType": "MySQL-instance",
  "parentUuid": "eae13a37-e089-4272-930b-d057c72bdf45",
  "extendInfo": {
    "hostId": "eae13a37-e089-4272-930b-d057c72bdf45",
    "instancePort": "3306",
    "isTopInstance": "1"
  },
  "dependencies": {
    "agents": [
      {
        "uuid": "eae13a37-e089-4272-930b-d057c72bdf45"
      }
    ]
  },
  "auth": {
    "authType": "123",
    "authKey": 123,
    "authPwd": "sfgasgfasfgafg",
    "extendInfo": {
      "instancePort": 3306
    }
  }
}
