=== robbiewu008/open-eBackup/src/ProtectManager/component/PM_System_Base_Common_Service/src/pm-plugins/pm-database-plugins/pm-tidb-protection-plugin/src/main/resources/jsonschema/TiDB-cluster_define.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "title",
  "properties": {
    "name": {
      "type": "string",
      "description": "集群实例名称",
      "minLength": 1
    },
    "type": {
      "type": "string",
      "description": "资源类型"
    },
    "subType": {
      "type": "string",
      "description": "资源子类型"
    },
    "auth": {
      "$ref": "classpath:jsonschema/TiDB-base.json#/auth"
    },
    "extendInfo": {
      "type": "object",
      "properties": {
        "tiupUuid": {
          "type": "string",
          "description": "tiup节点uuid",
          "minLength": 1,
          "maxLength": 128
        },
        "clusterName": {
          "type": "string",
          "description": "集群名字",
          "minLength": 1,
          "maxLength": 512
        },
        "logBackupPath": {
          "type": "string",
          "description": "logBackupPath",
          "minLength": 1,
          "maxLength": 1024
        },
        "clusterInfoList": {
          "type": "string",
          "description": "集群配置信息",
          "minLength": 1
        },
        "version": {
          "type": "string",
          "description": "集群版本",
          "minLength": 1,
          "maxLength": 128
        },
        "owner": {
          "type": "string",
          "description": "集群归属",
          "minLength": 1,
          "maxLength": 512
        },
        "tiupPath": {
          "type": "string",
          "description": "tiup安装路径",
          "minLength": 1,
          "maxLength": 1024
        }
      },
      "required": [
        "tiupUuid",
        "clusterName",
        "logBackupPath",
        "clusterName",
        "version",
        "owner",
        "tiupPath"
      ]
    },
    "dependencies": {
      "$ref": "classpath:jsonschema/TiDB-base.json#/agentDependencies"
    }
  },
  "required": [
    "subType",
    "type",
    "name",
    "dependencies",
    "auth",
    "extendInfo"
  ]
}

=== robbiewu008/open-eBackup/src/ProtectManager/component/PM_System_Base_Common_Service/src/pm-plugins/pm-database-plugins/pm-tidb-protection-plugin/src/test/resources/Cluster-req.json
{
  "name":"test",
  "type":"Database",
  "subType":"TiDB-cluster",
  "extendInfo":{
    "tiupUuid":"c2f26f36-c4f9-43cc-8fdd-1a8ded788bf5",
    "tiupPath": "/opt/demo",
    "clusterName":"tidb-test",
    "logBackupPath":"/dev",
    "clusterInfoList":"[{\"id\":\"8.40.146.172:2379\",\"role\":\"pd\",\"host\":\"8.40.146.172\",\"status\":\"up\",\"parent\":null,\"hostManagerIp\":\"192.168.146.172\",\"hostManagerResourceUuid\":\"12300eb1-2be9-44db-b050-a4af8a85eb95\"},{\"id\":\"8.40.146.173:2379\",\"role\":\"pd\",\"host\":\"8.40.146.173\",\"status\":\"up\",\"parent\":null,\"hostManagerIp\":\"192.168.146.173\",\"hostManagerResourceUuid\":\"a50086f2-0418-42bf-8378-eacd20a66b0c\"},{\"id\":\"8.40.146.179:2379\",\"role\":\"pd\",\"host\":\"8.40.146.179\",\"status\":\"up\",\"parent\":null,\"hostManagerIp\":\"192.168.146.179\",\"hostManagerResourceUuid\":\"ff4dd354-c0cb-4580-8ffb-e27e82cc980c\"},{\"id\":\"8.40.146.170:4000\",\"role\":\"tidb\",\"host\":\"8.40.146.170\",\"status\":\"up\",\"parent\":null,\"hostManagerIp\":\"192.168.146.170\",\"hostManagerResourceUuid\":\"ca297641-c6a1-4578-b400-83e9a71f4d0b\"},{\"id\":\"8.40.146.171:4000\",\"role\":\"tidb\",\"host\":\"8.40.146.171\",\"status\":\"up\",\"parent\":null,\"hostManagerIp\":\"192.168.146.171\",\"hostManagerResourceUuid\":\"4a5bd0db-0197-4411-a765-4da8afe097b7\"},{\"id\":\"8.40.146.175:20160\",\"role\":\"tikv\",\"host\":\"8.40.146.175\",\"status\":\"up\",\"parent\":null,\"hostManagerIp\":\"192.168.146.175\",\"hostManagerResourceUuid\":\"7e7ad259-d00c-4707-a349-851f1cef4188\"},{\"id\":\"8.40.146.176:20160\",\"role\":\"tikv\",\"host\":\"8.40.146.176\",\"status\":\"up\",\"parent\":null,\"hostManagerIp\":\"192.168.146.176\",\"hostManagerResourceUuid\":\"5d6e4be0-b92e-4167-9915-b81e47a4edc1\"},{\"id\":\"8.40.146.178:20160\",\"role\":\"tikv\",\"host\":\"8.40.146.178\",\"status\":\"up\",\"parent\":null,\"hostManagerIp\":\"192.168.146.178\",\"hostManagerResourceUuid\":\"ffd4b69b-420b-447a-9639-0522bf4b7431\"}]",
    "version":"v7.0.0",
    "owner":"tidb",
    "save_type":0
  },
  "dependencies":{
    "agents":[
      {
        "uuid":"c2f26f36-c4f9-43cc-8fdd-1a8ded788bf5",
        "endpoint":"192.168.146.174"
      }
    ]
  },
  "auth":{
    "authType":8,
    "authKey":"backup",
    "authPwd":"Huawei@123"
  }
}
